name: randomStudents

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4.1.5

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.12' # 指定 Python 版本

    - name: instsall_numpy
      run: pip install numpy

    - name: Pull
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git pull

    - name: Run Python script
      run: python ./posts/randomStudents/randomGenerator.py # 指定要运行的 Python 脚本路径

    - name: Commit and push if changed
      run: |
        git add . # 添加当前目录及其子目录中的更改到暂存区
        git commit -m "Update myfile.txt" || exit 0
        git push
